    import Head from 'next/head';
    import HomePage from '@/src/components/home/home-page';
    
    export type dataType = {
        description? : string,
        id : string,
        image : string,
        title : string,
    }

    export type dataTypeGlobal = {
        data : dataType[]
    }

    export default function Home({ data } : dataTypeGlobal) {
    return (

        <div>
        <Head>
            <title>Events app</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <HomePage data={data}/>
        </main>
    </div>

    );

    }

    export async function getServerSideProps() {
    const { events_categories } : any = await import('../data/dataFolder.json');
    return {
        props: {
        data: events_categories,
        },
    };
    
    }